# This is an appspec.yml template file for use with an EC2 deployment in CodeDeploy.
# For help completing this file, see the "AppSpec File Reference" in the  
#   "CodeDeploy User Guide" at
#   https://docs.aws.amazon.com/codedeploy/latest/userguide/app-spec-ref.html

# Fixed and used by CodeDeploy, DO NOT CHANGE
version: 0.0

# linux xor windows
os: linux 

# During the Install deployment lifecycle event, copy the specified files
#   in "source" starting from the root of the revision's file bundle 
#   to "destination" on the Amazon EC2 instance.
# Specify multiple "source" and "destination" pairs if you want to copy 
#   from multiple sources or to multiple destinations.
files:
  - source: docs/
    destination: /home/ec2-user/potato/docs/
  - source: potato-website/
    destination: /home/ec2-user/potato/app/
  - source: requirements.txt
    destination: /home/ec2-user/potato/

hooks:
# For each deployment lifecycle event, specify multiple "location" entries 
#   if you want to run multiple scripts during that event.
# You can specify "timeout" as the number of seconds to wait until failing the deployment 
#   if the specified scripts do not run within the specified time limit for the 
#   specified event. For example, 900 seconds is 15 minutes. If not specified, 
#   the default is 1800 seconds (30 minutes).
#   Note that the maximum amount of time that all scripts must finish executing 
#   for each individual deployment lifecycle event is 3600 seconds (1 hour). 
#   Otherwise, the deployment will stop and CodeDeploy will consider the deployment
#   to have failed to the Amazon EC2 instance. Make sure that the total number of seconds 
#   that are specified in "timeout" for all scripts in each individual deployment 
#   lifecycle event does not exceed a combined 3600 seconds (1 hour).
# For deployments to Amazon Linux, Ubuntu Server, or RHEL instances,
#   you can specify "runas" in an event to
#   run as the specified user. For more information, see the documentation.
# If you do not want to run any commands during a particular deployment
#   lifecycle event, remove that event declaration altogether. Blank or 
#   incomplete event declarations may cause associated deployments to fail.
# All the scripts specified in "location" start from the root of the revision's file bundle.
# The runas seems optional
  ApplicationStop:
    - location: deploy/stop-app.sh
      timeout: 10
      runas: ec2-user

#  BeforeInstall:
#    - location:
#      timeout:
#      runas:

  AfterInstall:
    - location: deploy/install-dependencies.sh
      timeout: 180
      runas: ec2-user
    - location: deploy/build-docs.sh
      timeout: 180
      runas: ec2-user
    - location: deploy/config-app.sh
      timeout: 180
      runas: ec2-user

  ApplicationStart:
    - location: deploy/start-app.sh
      timeout: 10
      runas: ec2-user

#  ValidateService:
#    - location:
#      timeout:
#      runas:
