name: main-integration

on:
  # Triggers the workflow on push to the main branch
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Sets up the Python 3.10 environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Installs dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executes tests
        run: python potato-website/manage.py test

  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Builds documentation
        uses: ammaraskar/sphinx-action@0.4

      - name: Deploys documentation
        run: echo TODO deploy docs somewhere