name: main

on:
  # Triggers the workflow on push to the main branch
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
      AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
      AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup Python 3.10 environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute tests
        run: python potato-website/manage.py test

  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Build documentation
        run: |
          pip install sphinx
          pushd docs
          make html
          popd

      - name: Deploy documentation
        run: echo TODO deploy docs somewhere